### PR TITLE
Document RQ HerokuWorker class

### PR DESCRIPTION
**Pull request by adamchainz**
For https://github.com/scoutapp/scout_apm_python/pull/530.

### CODE REVIEW

**Comment by jrothrock** [comment]
Thanks for the quick turnaround!

**Comment by adamchainz** [comment]
I should have written something, but I normally wouldn't merge this until the release is out, as it's not going to work for new customers until then. In the past I've had to ask for docs merges, you're also giving a quick turnaround :)

**Comment by jrothrock** [comment]
Ahh that was my bad. I saw the Python repo had a merge for "RQ Heroku" and assumed. I should have asked

**Comment by jrothrock** [comment]
I re-deployed the last commit. Let me know know when I should deploy this one :)

**Pull request merged**
