### PR TITLE
Improve Python documentation

### PR DESCRIPTION
**Pull request by adamchainz**
* Link to PyPI package
* Alphabetically sort list of frameworks to make them easier to search and prevent appearance of favouritism
* Many small phrasing and grammar fixes

### CODE REVIEW

**Comment by adamchainz** [comment]
@dlanderson please review and merge :)

**Comment by adamchainz** [comment]
For testing, `vagrant up` didn't work, so I pulled in the latest from [lord/slate](https://github.com/lord/slate). I tried doing a merge PR like @itsderek23 did in #4 but there were a bunch of conflicts and I wasn't sure which files were safe to take - I guess everything not in `source/` but maybe there's some customization?

**Comment by itsderek23** [comment]
@adamchainz - sorry for the issues.

> For testing, vagrant up didn't work

Sorry - a bit confused. Did I miss this in instructions for running the docs locally? I didn't think this was needed.

> but there were a bunch of conflicts and I wasn't sure which files were safe to take - I guess everything not in source/ but maybe there's some customization?

I don't see any conflicts in the PR right now:

image

**Comment by adamchainz** [comment]
> Sorry - a bit confused. Did I miss this in instructions for running the docs locally? I didn't think this was needed.

Using vagrant was the easiest way for me to get the right version of ruby and its dependencies. Using my brew'd ruby on macOS I got errors during install like:

```
ERROR: While executing gem ...
(NameError) uninitialized constant Gem::SafeYAML
```

and after a quick google it looked like that was due to my newer Ruby/Gem/Bundler version. I'm not a Ruby dev so I thought using the `Vagrantfile` would be quicker.

Yes it's not in the docs here, but the `Vagrantfile` is (and the `Dockerfile` too), but it is in the upstream docs.

> I don't see any conflicts in the PR right now:

Sorry - I meant I had conflicts merging in the upstream `lord/slate` as you did in #4 so I didn't even make a PR. I tried again now and succeeded - see #46.

**Pull request merged**
