### PR TITLE
Revert "Document RQ HerokuWorker class"

### PR DESCRIPTION
**Pull request by jrothrock**
Reverts scoutapp/slate_apm_help#102

### CODE REVIEW

**Comment by adamchainz** [comment]
Why?

**Comment by jrothrock** [comment]
@adamchainz Has this been created?

**Comment by adamchainz** [comment]
It was already created when I made #102. I linked to its PR, which I merged around the tmie I made the docs PR: https://github.com/scoutapp/scout_apm_python/pull/530 .

The reason I said about holding back on the docs is that I normally don't ask for docs changes to be merged and released until the code chagne has been released. Otherwise someone could follow the setup instructions and try something that isn't yet available. It wasn't such a big problem here though because RQ on Heroku is not likely to be very popular.

The code change was released in version 2.15.0, a few days ago. This can always be seen in the changelog: https://github.com/scoutapp/scout_apm_python/blob/master/CHANGELOG.md

**Comment by jrothrock** [comment]
Yeah I remember that. Sorry I thought the PR was like tiding it over for another PR later or something. I now know what you mean

**Comment by adamchainz** [comment]
👍 

I just reread your comment about re-deploying a commit. I forgot about that, sorry. I have generally believed the docs were auto-deployed from whatever gets merged.

**Comment by jrothrock** [comment]
Oh no worries I totally forgot about it as well

Yeah we still have to deploy. We're loosely thinking about redoing all of the docs so we'd probably change it then

**Pull request closed without merging**
